# Generated by Django 6.0.7 on 2026-08-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Üniversite Adı')),
                ('city', models.CharField(default='Diğer', max_length=100, verbose_name='Şehir')),
                ('uni_type', models.CharField(choices=[('Devlet', 'Devlet'), ('Vakıf', 'Vakıf'), ('KKTC', 'KKTC'), ('Yabancı', 'Yabancı'), ('Bilinmiyor', 'Bilinmiyor')], default='Devlet', max_length=50, verbose_name='Üniversite Türü')),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Program Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Program / Bölüm Adı')),
                ('clean_name', models.CharField(max_length=255, verbose_name='Temiz Bölüm Adı')),
                ('degree', models.CharField(default='Lisans (4+ Yıl)', max_length=50, verbose_name='Öğrenim Derecesi')),
                ('score_type', models.CharField(default='SAY', max_length=20, verbose_name='Puan Türü')),
                ('duration', models.IntegerField(default=4, verbose_name='Süre (Yıl)')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='analytics.university', verbose_name='Üniversite')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programlar',
                'ordering': ['university__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('general_quota', models.IntegerField(default=0, verbose_name='Genel Kontenjan')),
                ('top_school_quota', models.IntegerField(default=0, verbose_name='Okul Birincisi Kontenjanı')),
                ('total_quota', models.IntegerField(default=0, verbose_name='Toplam Kontenjan')),
                ('min_score', models.FloatField(blank=True, null=True, verbose_name='En Düşük Puan')),
                ('min_ranking', models.IntegerField(blank=True, null=True, verbose_name='En Düşük Sıralama')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Kapatıldı mı?')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yeni Açıldı mı?')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_records', to='analytics.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Kontenjan Kaydı',
                'verbose_name_plural': 'Kontenjan Kayıtları',
                'ordering': ['year', 'program'],
                'unique_together': {('program', 'year')},
            },
        ),
    ]
